version: '3.3'
services:
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: jassisti
      MYSQL_DATABASE: jassisti
      MYSQL_USER: jassisti
      MYSQL_PASSWORD: jassisti
    ports:
    - "3306:3306"
